# Generated by Django 4.1.4 on 2023-11-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(choices=[('passed', 'Passed'), ('active', 'Active'), ('failed', 'Failed'), ('deleted', 'Deleted')], max_length=10)),
                ('student_score', models.FloatField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_result', models.CharField(choices=[('acc', 'Accepted'), ('rjc', 'Rejected')], max_length=10)),
                ('student_explanation', models.TextField(blank=True, null=True)),
                ('educational_assistant_explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentCertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_certificate', models.FileField(upload_to='')),
                ('place_of_issue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReconsiderationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconsideration_text', models.TextField()),
                ('reconsideration_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_status', models.CharField(choices=[('not send', 'Not Send'), ('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='Not Send', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RemovalAndExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('failed', 'Failed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100)),
                ('unit_selection_start_time', models.DateTimeField()),
                ('unit_selection_end_time', models.DateTimeField()),
                ('courses_start_time', models.DateField()),
                ('courses_end_time', models.DateField()),
                ('repairing_unit_selection_start_time', models.DateTimeField()),
                ('repairing_unit_selection_end_time', models.DateTimeField()),
                ('emergency_deletion_end_time', models.DateTimeField()),
                ('exams_start_time', models.DateField()),
                ('term_end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TermCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_days_and_times', models.JSONField(help_text='Select class days and times in JSON format')),
                ('exam_time', models.DateTimeField(blank=True, null=True)),
                ('exam_place', models.CharField(blank=True, max_length=100, null=True)),
                ('course_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TermRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_result', models.CharField(choices=[('acc', 'Accepted'), ('rjc', 'Rejected')], max_length=10)),
                ('student_explanation', models.TextField(blank=True, null=True)),
                ('with_academic_years', models.BooleanField()),
                ('educational_assistant_explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
