# Generated by Django 4.1.4 on 2023-11-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('term', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termremovalrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='termremovalrequest',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='termcourse',
            name='course_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.professor'),
        ),
        migrations.AddField(
            model_name='termcourse',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.approvedcourse'),
        ),
        migrations.AddField(
            model_name='termcourse',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term.term'),
        ),
        migrations.AddField(
            model_name='term',
            name='professor_registered',
            field=models.ManyToManyField(blank=True, related_name='registered_term_professor', to='account.professor'),
        ),
        migrations.AddField(
            model_name='term',
            name='students_registered',
            field=models.ManyToManyField(blank=True, related_name='registered_term_students', to='account.student'),
        ),
        migrations.AddField(
            model_name='term',
            name='term_courses',
            field=models.ManyToManyField(blank=True, related_name='courses_term', to='term.termcourse'),
        ),
        migrations.AddField(
            model_name='removalandextensionrequest',
            name='extended_courses',
            field=models.ManyToManyField(related_name='extended_courses', to='term.termcourse'),
        ),
        migrations.AddField(
            model_name='removalandextensionrequest',
            name='removed_courses',
            field=models.ManyToManyField(related_name='removed_courses', to='term.registrationrequest'),
        ),
        migrations.AddField(
            model_name='removalandextensionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='term.termcourse'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term.term'),
        ),
        migrations.AddField(
            model_name='reconsiderationrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termcourse'),
        ),
        migrations.AddField(
            model_name='reconsiderationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='enrollmentcertificaterequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='enrollmentcertificaterequest',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='emergencyremovalrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termcourse'),
        ),
        migrations.AddField(
            model_name='emergencyremovalrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term.termcourse'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='term_taken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term.term'),
        ),
    ]
