# Generated by Django 4.1.4 on 2023-11-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.coursestudent', unique=True),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='reconsideration_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconsiderationrequest',
            name='reconsideration_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
