version: "3.8"

services:

  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=golestan
      - POSTGRES_DB=golestan
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - 5432
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    restart: always
    depends_on:
      - db
  
  app:
    build: ./
    container_name: app
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=golestan
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  
volumes:
  postgres_data: