version: '1.0'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - data:/data
    environment:
      - "MINIO_ROOT_USER:admin"
      - "MINIO_ROOT_PASSWORD=admin"
    command: server /data --console-address :9090
  createbucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 http://minio:9000 user password;
      /usr/bin/mc mb s3/static/;
      "
  django_golestan:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - minio
      - createbucket